language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: e96emK490NxG9jfLhkyzqk4QfhQLfr6O8SwEO0N3a3DAMXjlhlF2NhYZaqYpLWvPTQHO2xLHG7+IOEL2/gr4rI1F8NNgLoJlCBSAHN0gMsh8+UFxojphnFiO+vmLEMBUxoVSZkqkrNmLUBzgVttuk7E6njUdNgGNVz1NqmOxRiA3VMEWpQpsiiv9P5JXI/rsd7WrHTjmsEavbr0QxlpCyViIZHamL78C9LT5+6D8/1A/ZFeiuEiLdXGbsHNsA6EwFety64nCJeMEWREYt12inEPxhG9/W8Qx9UA5Suwijr+dScsHYfImFCaXzENRHo6RohZvgPe8+H44aAjRChEcxXLJg0Ioy7g+7pHXv/u0nM3cDd0FBZYwQmo0TT88riCI/1zczOB0LCTSACNHVxg6i8ynCoZtzLaGbLM5JcK8Ec9WHa4hdx7lOns5l5WY+AOB2Il9BLhBwQddh97e7lZC22477v68vm3k3vw7CaJz1ZTy/B1Tn8fZ6w1yHmhqxXo5ISJjaQuJIGYmhHdenpOMO346Z7+jgIFUiT8XBmeGgtQZQ/2kB3UVPl1mWJ6lx8k28763n+AlnWlKklnEkhNSZMYUy7mfhfO6F6H6idVLLPwQJtYeMoNSgWV449W/9kDyjij74s7r1VKbZmUsESp//Bjrz7p5DxcXfN9LFJaKIkQ=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
