language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: PobNSu4I6vjak2FNFtG8ntxPnwjH+6s6MwKQswLd4suJ9aWB5nJNKXt6RTJ0n5edLmtoHAE4yd8v0IuT/N0h0+eLxZb8q+T8+PQurwJsFpX6JQeqYgKspsuW/9RMyqztisYaV0xduezt5JTzwq8qCX6bj5X4kLF2bfnKgbtE2uvAk/OmaVEXNXk26cjO+8UYTNd6D8yhJT1dxtycbWz0bczllsj2zLF1tO0+D3TW+5So3kazk5B+3H8Yh9Xt5vNRiEsLvHkhg4ZaTbTWPiOjkIAhzw429XBQEOzD1y6xzJFn4jtGJh2/K8reYnJ+w4ONMckW388sCunjiOuWp+obWLwGdBuG3SG/3TW+kBybCBauOpSGBvlI/pbV6kkNVV4k9c+9+6inP72vSLbMCLmyroQC15QLgzUu6xehubEGzaZg04rD1DyqhnKeXiHDlHxShAJyeOHLKCcAM3MibzUGmBMcghiL60UODunMYFf76MMrBbx6ioZ8zHEJT05A7r8gt/HfUXdYLyMWirlstcnzobnXrV/rP5IgPksKAisaGm9cczN+fDCk+/IwyH7ZUTxSyUj0l1Bd6YIUuqSNUWke5COYZJVQi1p9TPJqG7zddv8b9JRFdcmz0Ouwau53MWpk8Vi+vHuvNDvfqBtnhuF0XnOXR2yFyBIWI+sNuKy2l6A=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
